In [0]:
import numpy as np

In [2]:
my_list=[1,2,3,4]
type(np.array(my_list))

numpy.ndarray

In [3]:
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [0]:
print(arr.shape)


(4,)


In [4]:
np.arange(0,10)
#np.arange(0,15,3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#np.zeros(5)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.linspace(0,11,10)
#np.linespace(0,11,5000)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [8]:
np.random.randint(0,10)

8

In [9]:
np.random.randint(0,1000,(3,3))

array([[225, 649,  12],
       [225, 955, 382],
       [ 80, 476, 528]])

In [10]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [11]:
ar=np.array([[1,2,3,4],[5,6,7,8],[1,3,4,5]])
print(ar.shape)

(3, 4)


In [12]:
ar.T

array([[1, 5, 1],
       [2, 6, 3],
       [3, 7, 4],
       [4, 8, 5]])

In [0]:
newshape =ar.reshape((6,2))
print(newshape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 3]
 [4 5]]


In [0]:
ar.max()

8

In [0]:
ar.min()

1

In [0]:
ar.mean()

4.083333333333333

In [0]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
mat[0,3]

3

In [0]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [0]:
f=mat<50
mat[f]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])